# Generated by Django 5.0.8 on 2024-08-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedlink',
            name='remove_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
