# Generated by Django 5.0.10 on 2024-12-22 03:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_alter_shortenedlink_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedlink',
            name='shortened_link',
            field=models.CharField(blank=True, db_index=True, error_messages={'max_length': 'Shortened link must be at most 10 characters long', 'unique': 'This shortened link already exists'}, help_text='The shortened URL path', max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Shortened link must be alphanumeric with hyphens and underscores only', regex='^[a-zA-Z0-9-_]*$')], verbose_name='Shortened URL'),
        ),
    ]
