# Generated by Django 5.0.10 on 2024-12-26 23:13

import django.core.validators
import django.db.models.deletion
import sbily.links.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_alter_shortenedlink_shortened_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedShortenedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_link', models.URLField(help_text='The original URL that will be shortened', max_length=2000, verbose_name='Original URL')),
                ('shortened_link', models.CharField(blank=True, db_index=True, error_messages={'max_length': 'Shortened link must be at most 10 characters long', 'unique': 'This shortened link already exists'}, help_text='The shortened URL path', max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Shortened link must be alphanumeric with hyphens and underscores only', regex='^[a-zA-Z0-9-_]*$')], verbose_name='Shortened URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this shortened link was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this shortened link was last updated', verbose_name='Updated At')),
                ('remove_at', models.DateTimeField(blank=True, db_index=True, help_text='When this link should be automatically removed', null=True, validators=[sbily.links.models.future_date_validator], verbose_name='Remove At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this shortened link is active', verbose_name='Is Active')),
                ('removed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this shortened link was removed', verbose_name='Removed At')),
                ('user', models.ForeignKey(help_text='User who created this shortened link', on_delete=django.db.models.deletion.CASCADE, related_name='deleted_shortened_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deleted Shortened Link',
                'verbose_name_plural': 'Deleted Shortened Links',
                'ordering': ['-removed_at'],
            },
        ),
    ]
