# Generated by Django 5.0.11 on 2025-01-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_deletedshortenedlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedshortenedlink',
            name='time_until_permanent_deletion',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, help_text='When this shortened link will be permanently deleted', null=True, verbose_name='Time Until Permanent Deletion'),
        ),
    ]
