# Generated by Django 5.0.11 on 2025-02-03 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0007_deletedshortenedlink_time_until_permanent_deletion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortenedlink',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Shortened Link', 'verbose_name_plural': 'Shortened Links'},
        ),
        migrations.DeleteModel(
            name='DeletedShortenedLink',
        ),
    ]
