FROM dkshs/python_dev:latest

ARG BUILD_ENVIRONMENT=local

ENV BUILD_ENV ${BUILD_ENVIRONMENT}

USER ${USERNAME}

COPY ./requirements .
RUN pip install -r ${BUILD_ENVIRONMENT}.txt

COPY --chown=${USERNAME}:${USERNAME} . .

CMD [ "./.docker/start.sh" ]
