# Generated by Django 5.0.10 on 2024-12-18 01:35

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, editable=False, help_text='Unique token string', max_length=255, unique=True)),
                ('type', models.CharField(choices=[('email_verification', 'Email Verification'), ('password_reset', 'Password Reset')], default='email_verification', help_text='Type of token', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 18, 3, 35, 20, 999609, tzinfo=datetime.timezone.utc), help_text='Token expiration date and time')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User this token belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(fields=('user', 'type'), name='unique_user_token_type'),
        ),
        migrations.AlterIndexTogether(
            name='token',
            index_together={('user', 'type', 'created_at')},
        ),
    ]
