# Generated by Django 5.0.10 on 2024-12-18 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_token_token_unique_user_token_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 18, 3, 40, 41, 227822, tzinfo=datetime.timezone.utc), editable=False, help_text='Token expiration date and time'),
        ),
    ]
