# Generated by Django 5.0.10 on 2024-12-18 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 18, 3, 47, 8, 554548, tzinfo=datetime.timezone.utc), editable=False, help_text='Token expiration date and time'),
        ),
    ]
