# Generated by Django 5.0.10 on 2024-12-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(db_index=True, editable=False, help_text='Token expiration date and time'),
        ),
    ]
