# Generated by Django 5.0.10 on 2024-12-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_token_user_type_created_at_users_token_user_id_ea9964_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_num_links',
            field=models.PositiveIntegerField(default=5, help_text='Maximum number of links a user can create', verbose_name='max number of links'),
        ),
        migrations.AddField(
            model_name='user',
            name='max_num_links_temporary',
            field=models.PositiveIntegerField(default=2, help_text='Maximum number of temporary links a user can create', verbose_name='max number of temporary links'),
        ),
    ]
