# Generated by Django 5.0.10 on 2024-12-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_max_num_links_user_max_num_links_temporary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_with_email',
            field=models.BooleanField(default=False, help_text='Designates whether the user can login with email.', verbose_name='login with email'),
        ),
    ]
