# Generated by Django 5.0.10 on 2025-01-07 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_token_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='type',
            field=models.CharField(choices=[('email_verification', 'Email Verification'), ('sign_in_with_email', 'Sign In With Email'), ('password_reset', 'Password Reset'), ('activate_account', 'Activate Account')], default='email_verification', help_text='Type of token', max_length=20),
        ),
    ]
