# Generated by Django 5.0.11 on 2025-01-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='type',
            field=models.CharField(choices=[('email_verification', 'Email Verification'), ('change_email', 'Change Email'), ('sign_in_with_email', 'Sign In With Email'), ('password_reset', 'Password Reset'), ('activate_account', 'Activate Account')], default='email_verification', help_text='Type of token', max_length=20),
        ),
    ]
