#!/bin/bash

if [ "$RUN_COLLECTSTATIC" = "True" ]; then
  python /app/manage.py collectstatic --noinput
fi
if [ "$RUN_MIGRATIONS" = "True" ]; then
  python /app/manage.py migrate --noinput
fi
exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:${PORT} --chdir=/app
